package View;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import TAB2MXL.Measure;
import TAB2MXL.XmlGenerator;

class StringParserUtilityTest {

	@BeforeEach
	void setUp() throws Exception {
	}

	@Test
	void testSimple() throws Exception {
		String res = Controller.cleanup("|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n"
				+ "|---2-------------|-2---------------|\n"
				+ "|-0---------------|-0---------------|\n"
				+ "");
		StringParserUtility.clearMeasureList();
		ArrayList<Measure> measureList = StringParserUtility.stringParse(res);
		String result = XmlGenerator.Generate(measureList, "GUITAR");
		assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
				+ "<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\n"
				+ "<score-partwise version=\"3.1\">\n"
				+ "    <part-list>\n"
				+ "        <score-part id=\"P1\">\n"
				+ "            <part-name>GUITAR</part-name>\n"
				+ "        </score-part>\n"
				+ "    </part-list>\n"
				+ "    <part id=\"P1\">\n"
				+ "        <measure number=\"1\">\n"
				+ "            <attributes>\n"
				+ "                <divisions>16</divisions>\n"
				+ "                <key>\n"
				+ "                    <fifths>0</fifths>\n"
				+ "                </key>\n"
				+ "                <time>\n"
				+ "                    <beats>4</beats>\n"
				+ "                    <beat-type>4</beat-type>\n"
				+ "                </time>\n"
				+ "                <clef>\n"
				+ "                    <sign>TAB</sign>\n"
				+ "                    <line>5</line>\n"
				+ "                </clef>\n"
				+ "                <staff-details>\n"
				+ "                    <staff-lines>6</staff-lines>\n"
				+ "                    <staff-tuning line=\"1\">\n"
				+ "                        <tuning-step>E</tuning-step>\n"
				+ "                        <tuning-octave>2</tuning-octave>\n"
				+ "                    </staff-tuning>\n"
				+ "                    <staff-tuning line=\"2\">\n"
				+ "                        <tuning-step>A</tuning-step>\n"
				+ "                        <tuning-octave>2</tuning-octave>\n"
				+ "                    </staff-tuning>\n"
				+ "                    <staff-tuning line=\"3\">\n"
				+ "                        <tuning-step>D</tuning-step>\n"
				+ "                        <tuning-octave>3</tuning-octave>\n"
				+ "                    </staff-tuning>\n"
				+ "                    <staff-tuning line=\"4\">\n"
				+ "                        <tuning-step>G</tuning-step>\n"
				+ "                        <tuning-octave>3</tuning-octave>\n"
				+ "                    </staff-tuning>\n"
				+ "                    <staff-tuning line=\"5\">\n"
				+ "                        <tuning-step>B</tuning-step>\n"
				+ "                        <tuning-octave>3</tuning-octave>\n"
				+ "                    </staff-tuning>\n"
				+ "                    <staff-tuning line=\"6\">\n"
				+ "                        <tuning-step>E</tuning-step>\n"
				+ "                        <tuning-octave>4</tuning-octave>\n"
				+ "                    </staff-tuning>\n"
				+ "                </staff-details>\n"
				+ "            </attributes>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>E</step>\n"
				+ "                    <octave>2</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>2</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>6</string>\n"
				+ "                        <fret>0</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>B</step>\n"
				+ "                    <octave>2</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>2</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>5</string>\n"
				+ "                        <fret>2</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>E</step>\n"
				+ "                    <octave>3</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>2</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>4</string>\n"
				+ "                        <fret>2</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>G</step>\n"
				+ "                    <octave>3</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>2</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>3</string>\n"
				+ "                        <fret>1</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>B</step>\n"
				+ "                    <octave>3</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>2</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>2</string>\n"
				+ "                        <fret>0</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>E</step>\n"
				+ "                    <octave>4</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>2</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>1</string>\n"
				+ "                        <fret>0</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>B</step>\n"
				+ "                    <octave>3</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>2</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>2</string>\n"
				+ "                        <fret>0</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>G</step>\n"
				+ "                    <octave>3</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>2</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>3</string>\n"
				+ "                        <fret>1</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "        </measure>\n"
				+ "        <measure number=\"2\">\n"
				+ "            <attributes>\n"
				+ "                <divisions>16</divisions>\n"
				+ "                <key>\n"
				+ "                    <fifths>0</fifths>\n"
				+ "                </key>\n"
				+ "                <time>\n"
				+ "                    <beats>4</beats>\n"
				+ "                    <beat-type>4</beat-type>\n"
				+ "                </time>\n"
				+ "            </attributes>\n"
				+ "            <note>\n"
				+ "                <pitch>\n"
				+ "                    <step>E</step>\n"
				+ "                    <octave>4</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>16</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>whole</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>1</string>\n"
				+ "                        <fret>0</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <pitch>\n"
				+ "                    <step>B</step>\n"
				+ "                    <octave>3</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>16</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>whole</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>2</string>\n"
				+ "                        <fret>0</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <pitch>\n"
				+ "                    <step>G</step>\n"
				+ "                    <octave>3</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>16</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>whole</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>3</string>\n"
				+ "                        <fret>1</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <pitch>\n"
				+ "                    <step>E</step>\n"
				+ "                    <octave>3</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>16</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>whole</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>4</string>\n"
				+ "                        <fret>2</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <pitch>\n"
				+ "                    <step>B</step>\n"
				+ "                    <octave>2</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>16</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>whole</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>5</string>\n"
				+ "                        <fret>2</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <pitch>\n"
				+ "                    <step>E</step>\n"
				+ "                    <octave>2</octave>\n"
				+ "                </pitch>\n"
				+ "                <duration>16</duration>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>whole</type>\n"
				+ "                <notations>\n"
				+ "                    <technical>\n"
				+ "                        <string>6</string>\n"
				+ "                        <fret>0</fret>\n"
				+ "                    </technical>\n"
				+ "                </notations>\n"
				+ "            </note>\n"
				+ "        </measure>\n"
				+ "    </part>\n"
				+ "</score-partwise>\n",result);
	}
	
	@Test
	void testDrumSimple() throws Exception {
		
		String res = Controller.cleanup("CC|x---------------|--------x-------|\n"
				+ "HH|--x-x-x-x-x-x-x-|----------------|\n"
				+ "SD|----o-------o---|oooo------------|\n"
				+ "HT|----------------|----oo----------|\n"
				+ "MT|----------------|------oo--------|\n"
				+ "BD|o-------o-------|o-------o-------|\n"
				+ "");
		StringParserUtility.clearMeasureList();
		ArrayList<Measure> measureList = StringParserUtilityDrum.stringParse(res);
		String result = XmlGenerator.Generate(measureList, "DRUMS");
		assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
				+ "<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\n"
				+ "<score-partwise version=\"3.1\">\n"
				+ "    <part-list>\n"
				+ "        <score-part id=\"P1\">\n"
				+ "            <part-name>DRUMS</part-name>\n"
				+ "            <score-instrument id=\"P1-I50\">\n"
				+ "                <instrument-name>Crash Cymbal 1</instrument-name>\n"
				+ "            </score-instrument>\n"
				+ "            <score-instrument id=\"P1-I36\">\n"
				+ "                <instrument-name>Bass Drum 1</instrument-name>\n"
				+ "            </score-instrument>\n"
				+ "            <score-instrument id=\"P1-I43\">\n"
				+ "                <instrument-name>Closed Hi Hat</instrument-name>\n"
				+ "            </score-instrument>\n"
				+ "            <score-instrument id=\"P1-I39\">\n"
				+ "                <instrument-name>Snare</instrument-name>\n"
				+ "            </score-instrument>\n"
				+ "        </score-part>\n"
				+ "    </part-list>\n"
				+ "    <part id=\"P1\">\n"
				+ "        <measure number=\"1\">\n"
				+ "            <attributes>\n"
				+ "                <divisions>16</divisions>\n"
				+ "                <key>\n"
				+ "                    <fifths>0</fifths>\n"
				+ "                </key>\n"
				+ "                <time>\n"
				+ "                    <beats>4</beats>\n"
				+ "                    <beat-type>4</beat-type>\n"
				+ "                </time>\n"
				+ "                <clef>\n"
				+ "                    <sign>percussion</sign>\n"
				+ "                    <line>2</line>\n"
				+ "                </clef>\n"
				+ "            </attributes>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>A</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I50\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "                <beam number=\"1\">begin</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>F</display-step>\n"
				+ "                    <display-octave>4</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I36\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <beam number=\"1\">end</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>G</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I43\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "                <beam number=\"1\">begin</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>G</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I43\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "                <beam number=\"1\">end</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>C</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I39\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <beam number=\"1\">begin</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>G</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I43\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "                <beam number=\"1\">end</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>G</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I43\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "                <beam number=\"1\">begin</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>F</display-step>\n"
				+ "                    <display-octave>4</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I36\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <beam number=\"1\">end</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>G</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I43\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "                <beam number=\"1\">begin</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>G</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I43\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "                <beam number=\"1\">end</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>C</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I39\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <beam number=\"1\">begin</beam>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>G</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>2</duration>\n"
				+ "                <instrument id=\"P1-I43\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>eighth</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "                <beam number=\"1\">end</beam>\n"
				+ "            </note>\n"
				+ "        </measure>\n"
				+ "        <measure number=\"2\">\n"
				+ "            <attributes>\n"
				+ "                <divisions>16</divisions>\n"
				+ "                <key>\n"
				+ "                    <fifths>0</fifths>\n"
				+ "                </key>\n"
				+ "                <time>\n"
				+ "                    <beats>4</beats>\n"
				+ "                    <beat-type>4</beat-type>\n"
				+ "                </time>\n"
				+ "            </attributes>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>C</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I39\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>F</display-step>\n"
				+ "                    <display-octave>4</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I36\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>C</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I39\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>C</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I39\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>C</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I39\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>E</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I48\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>E</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I48\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>D</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I46\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>D</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>1</duration>\n"
				+ "                <instrument id=\"P1-I46\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>16th</type>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>A</display-step>\n"
				+ "                    <display-octave>5</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>8</duration>\n"
				+ "                <instrument id=\"P1-I50\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>half</type>\n"
				+ "                <notehead>x</notehead>\n"
				+ "            </note>\n"
				+ "            <note>\n"
				+ "                <chord/>\n"
				+ "                <unpitched>\n"
				+ "                    <display-step>F</display-step>\n"
				+ "                    <display-octave>4</display-octave>\n"
				+ "                </unpitched>\n"
				+ "                <duration>8</duration>\n"
				+ "                <instrument id=\"P1-I36\"/>\n"
				+ "                <voice>1</voice>\n"
				+ "                <type>half</type>\n"
				+ "            </note>\n"
				+ "        </measure>\n"
				+ "    </part>\n"
				+ "</score-partwise>\n",result);
	}
	

}
